import Head from 'next/head'
import React, { useState, useContext, useRef, useEffect, useCallback } from 'react'
import type { NextPage } from 'next'
import { Header, Featured, Recommended, Footer } from '../components'
import { ScrollContext } from '../components/scrollobserver'
import { motion } from 'framer-motion'
import { HiChevronDoubleUp } from 'react-icons/hi'


const ScrollUp = () => {
  const handleScroll = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    e.preventDefault()
    document.getElementById('header')?.scrollIntoView()
  }
  return (
    <motion.button className='fixed top-[80%] right-12 z-50 bg-white w-8 h-8 rounded-full flex justify-center items-center shadow-lg shadow-gray-600/70 animate-pulse' onClick={(e) => handleScroll(e)}>
      <HiChevronDoubleUp />
    </motion.button>
  )
}

const Home: NextPage = () => {
  const [containerViewScroll, setContainerViewScroll] = useState(0)
  const containerRef = useRef<HTMLDivElement>(null)
  const { current: elContainer } = containerRef
  const { scrollY } = useContext(ScrollContext)

  const handleContainerHeight = useCallback(() => {
    setContainerViewScroll(scrollY - (elContainer?.clientHeight || 0))
  }, [scrollY, elContainer])

  useEffect(() => {
    return () => handleContainerHeight()
  }, [handleContainerHeight])

  return (
    <>
      <Head>
        <title>Animu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-screen min-h-screen relative box-border'>
        <div ref={containerRef} id='header'>
          <Header />
        </div>
        <Featured containerViewScroll={containerViewScroll} />
        <Recommended />
        <Footer />
        {containerViewScroll >= 0 ? <ScrollUp /> : ''}
      </main>
    </>
  )
}

export default Home
